type: object
properties:
    instance_type:
        type: string
        minLength: 1
    ami_type:
        type: string
        minLength: 1
    architecture:
        type: string
        minLength: 1
    root_device_type:
        type: string
        minLength: 1
    virtualization_type:
        type: string
        minLength: 1
    min_count:
        type: integer
        minLength: 1
    max_count:
        type: integer
        minLength: 1
    volumes:
        type: array
        minItems: 1
        contains:
            type: object
            properties:
                device:
                    type: string
                    minLength: 1
                size_gb:
                    type: integer
                    minLength: 1
                type:
                    type: string
                    minLength: 1
                mount:
                    type: string
                    minLength: 1
    users:
        type: array
        minItems: 1
        contains:
            type: object
            properties:
                login:
                    type: string
                    minLength: 1
                ssh_key:
                    type: string
                    minLength: 1
